---
title: " "
pagetitle: "Tomoharu Mori"
---

<br>

## Tomoharu Mori, Ph.D.

<br>

College of Comprehensive Psychology, Ritsumeikan University, JAPAN

2-150 Iwakura-cho

Ibaraki, Osaka 567-8570

Email: tmr15047 [atmark] fc.ritsumei.ac.jp

<br>

## Personal

<br>

Born on July 1986.

Citizenship: Japan

<br>

## Education

<br>

Ph.D. Economics, Graduate School of Economics, Osaka University, March 2014.

M.A. Economics, Graduate School of Economics, Osaka University, March 2011.

B.A. Commerce and Management, Faculty of Commerce and Management, Hitotsubashi University, March 2009.

<br>

## Working Experience

<br>

Associate Professor, College of Comprehensive Psychology, Ritsumeikan University, April 2017-present.

Post Doctoral Fellow, Research Institute for Socionetwork Strategies, Kansai University, October 2014-March 2017.

Specially Appointed Researcher, Institute for Social and Economic Research, April 2014-October 2014.

<br>

## Other Professional Positions

<br>

Researcher, Research Institute for Socionetwork Strategies, Kansai University, April 2018-present.

<br>

## Publications

<br>

See [Research](research.html) and [日本語の記事等](research_JPN).

<br>

## Fellowships

<br>

Grant-in-Aid for Challenging Research (Exploratory), Japan Society for the Promotion of Science, Research member (Leader: Masaru Sasaki), April 2020-present

Grand-in-Aid for Scientific Research (C), Japan Society for the Promotion of Science, Research member (Leader: Taizo Motonishi), April 2019-present

Grand-in-Aid for Scientific Research (A), Japan Society for the Promotion of Science, Research member (Leader: Katsuya Takii), April 2018-present

Topic-Setting Program to Advance Cutting-Edge Humanity and Social Science Research: Responding to Real Society, The Japan Society for the Promotion of Science, Research member (Leader: Masaru Sasaki), April 2016-March 2018.

Fund for Supporting Young Scholars, Kansai University, Research Leader, April 2016-March 2017.

Grand-in-Aid for Scientific Research (A), Japan Society for the Promotion of Science, Research member (Leader: Katsuya Takii), April 2015-March 2017.

Grand-in-Aid for Young Scientists (B), Japan Society for the Promotion of Science, Research Leader, April 2015-March 2016.

Research Fellowship for Young Scientists (DC2), Japan Society for the Promotion of Science, April 2012-March 2014.

Torii Fellowship, Suntory Foundation, September 2011-March 2012.

Invited participant, Asia Summer Institute of Behavioral Economics, National University of Singapore, July 2011.

<br>

## Professional Activities

<br>

### Membership

Association of Behavioral Economics and Finance, Association of Urban Housing Sciences, Economic Science Association, Japanese Economic Association, Japan Institute of Public Finance, The Japanese Psychological Association.

<br>

### Refereeing Activities

Journal of Economic Behavior & Organization, Kanematsu Prize, The Japanese Journal of Labor Studies.

<br>

### Program Organization and Committees

Commitee, Education and Reserch Commitee, The Japanese Psychological Association, 2021-2025.

Program Commitee, 15th annual meeting, Association of Behavioral Economics and Finance, 2021.

Exective Committee, 78th annual meeting, Japan Institute of Public Finance, 2021.

Committee, 4th Student Paper Award, Association of Behavioral Economics and Finance, 2021.

Program Commitee, 22nd Labor Economics Conference, 2019.

Program Commitee, 21st Labor Economics Conference, 2018.

Program Commitee, 20th Labor Economics Conference, 2017.

Organizer, Kansai Labor Seminar, October 2016-July 2019.

<br>

## Awards

<br>

Paper Award, Association of Urban Housing Sciences, 2015.

Encouragement Award, 7th Annual meeting of Association of Behavioral Economics and Finance, 2013.

The Highest Award for Poster Session, 16th Labor Economics Conference, 2013.

The Highest Award for Poster Session, 14th Labor Economics Conference, 2011.

<br>

# Research Presentations

<br>

2021: Tokyo Labor Economics Workshop.

2020: Osaka City University, Kansai University.

2019: Osaka University, Autumn meeting of Japanese Economic Association, Kansai Labor Seminar.

2018: Osaka University, 12th Annual Meeting of Association of Behavioral Economics and Finance.

2017: ESA Asia-Pacific Meeting, The 1st Workshop on Behavioral Economics of Social Norm and Public Moral.

2016: Meiji University.

2015: Kyoto University, Kyoto University Workshop on Experimental Economics, ESA World Meetings, ESA European Meeting, 9th Annual Meeting of Association of Behavioral Economics and Finance, Kansai University, CEE and RISS Seminar Series on Experimental Economics, The Osaka Workshop on Economics of Institutions and Organization.

2014:	Asia-Pacific ESA Conference, Workshop for Housing Sciences, Contract Theory Workshop East, ESA International Meetings, Autumn meeting of Japanese Economic Association, CEE and RISS Seminar Series on Experimental Economics, Kansai Labor Seinar.

2013: Asia-Pacific ESA Conference, OEIO Tokyo Conference: Spring, Spring meeting of Japanese Economic Association, 9th annual conference of the Asia-Pacific Economic Association, Asian Meeting of Econometric Society, Singapore Economic Review Conference, 16th Labor Economics Conference, 7th Annual Meeting of Association of Behavioral Economics and Finance.

2012: Applied Microeconomics Theory Workshop, 5th Trans-Pacific Labor Seminar, Kyoto Summer Workshop on Applied Economics, Contract Theory Workshop: Summer Camp in Shinshu, RIETI.

2011年	The Osaka Workshop on Economics of Institutions and Organizations, Spring meeting of Japanese Economic Association, 14th Labor Economics Conference, 6th Applied Econometrics Conference, Osaka Prefecture University.
