---
title: " "
pagetitle: "Tomoharu Mori"
---

<br>

## 論文（査読なし）

<br>

- **行動経済学が労働研究に与えうる影響**
  *日本労働研究雑誌*, 714, 3-13, 2020
  &nbsp;[Link](https://www.jil.go.jp/institute/zassi/backnumber/2020/01/pdf/003-013.pdf)

- **日本の小中高生はオンラインゲームにどれほど課金しているのか？：教室内アンケートを用いた分析**
  *情報通信学会誌*, 37, 47-52, 2019.（小川 一仁氏、川村 哲也氏、小山 友介氏、本西 泰三氏との共著）
  &nbsp;[Link](https://doi.org/10.11430/jsicr.37.1_47)

- **インターネットを利用した「経済実験」の動向と展望**
  *日本労働研究雑誌*, 705, 2-7, 2019.
  &nbsp;[Link](https://www.jil.go.jp/institute/zassi/backnumber/2019/04/pdf/002-007.pdf)
  
- **ニーデルレ＝ヴェスタールント「女性は競争嫌い？男性は競争しすぎ？」**
  *日本労働研究雑誌*, 660, 24-27, 2016.
  &nbsp;[Link](https://www.jil.go.jp/institute/zassi/backnumber/2016/04/pdf/024-027.pdf)

- **期限付きキャッシュバック制度が退去行動に与える影響：大阪市住宅供給公社の事例**
  *住宅土地経済*, 94, 29-35, 2014.
  （大竹文雄氏との共著、「都市住宅学」掲載論文の要約）

- **競争と再分配行動の関係性：経済実験による分析**
  *行動経済学*, 第７回大会プロシーディングス, 6, 81-84, 2013
  （大竹文雄氏、木成勇介氏、水谷徳子氏との共著） 
  &nbsp;[Link](https://doi.org/10.11167/jbef.6.81)

- **論文Today 何を与えれば、人はより働くのか？―フィールド実験による検証**
  *日本労働研究雑誌*、621、90-91、2012.
  &nbsp;[Link](https://www.jil.go.jp/institute/zassi/backnumber/2012/04/pdf/090-091.pdf)

- **労働課税の行動経済学的分析**
  *日本労働研究雑誌*, 605, 68-75, 2010.（大竹文雄氏との共著）
  &nbsp;[Link](https://www.jil.go.jp/institute/zassi/backnumber/2010/12/pdf/068-075.pdf)

<br>

## 書籍（分担執筆）

<br>

- **労働経済学における実験的手法**
  『日本の労働市場　経済学者の視点』川口大司編, 有斐閣, 第13章, 342-366, 2017.（佐々木勝氏と共著）
  &nbsp;[Link](http://www.yuhikaku.co.jp/books/detail/9784641165120)
  
- **最低賃金と労働者の「やる気」―経済実験によるアプローチ―」**
  『最低賃金改革：日本の働き方をいかに変えるか』, 大竹文雄・川口大司・鶴光太郎編著, 日本評論社, 第5章, 113-138, 2013.
  &nbsp;[Link](https://www.nippyo.co.jp/shop/book/6257.html)
  
- **最低賃金の決定過程と生活保護基準の検証**
  『最低賃金改革：日本の働き方をいかに変えるか』,
  大竹文雄・川口大司・鶴光太郎編著, 日本評論社, 139-168、2013.（玉田桂子氏との共著）
  &nbsp;[Link](https://www.nippyo.co.jp/shop/book/6257.html)

<br>

## 商業誌での記事

<br>

- **【座談会】論文の書き方はどう教えている？**
  *経済セミナー*, 721, 2021.

- **書評：ハロルド・ウィンター著『やりすぎの経済学』**
  *週刊読書人*, 3331, 6, 2020.

- **経済学者が読み解く現代社会のリアル　金融リテラシーの向上　プラスの影響だけ？**
  *週刊東洋経済*, 6907, 94-95, 2020.
  &nbsp;[Link](https://premium.toyokeizai.net/articles/-/22969)

- **最低賃金の決定過程と地域間格差の考察**
  *統計*, 70, 27-32, 2019.

- **最低賃金とは何か:決定要因と労働市場に与える影響**
  *経済セミナー*, 693, 43-47, 2017.

- **海外論文SURVEY vol.42　セルフコントロールと労働生産性：１年に渡るフィールド実験**
  *経済セミナー*, 674, 66-68. 2013.

- **海外論文SURVEY vol.39　私の給料・・・低すぎ？：賃金格差と仕事の満足度**
  *経済セミナー*, 671, 125-127, 2013.

- **海外論文SURVEY vol.35　ターゲットは１つではない：タクシー運転手の労働供給行動**
  *経済セミナー*, 668, 109-111, 2012.

- **海外論文SURVEY vol.31　お金持ちは利己的か？：所得と援助の関係性**
  *経済セミナー*, 665, 109-111, 2012.

- **海外論文SURVEY vol.26　社会的関係と労働生産性：友人の存在は生産性を上げるのか？**
  *経済セミナー*, 662, 121-123, 2011.

- **海外論文SURVEY vol.19　最低賃金は労働者の「公平感」に影響を与えるか？：実験室実験による検証**
  *経済セミナー*, 659, 108-110, 2011.

<br>

## 講演等

<br>

- **社会人のための行動経済学（ナッジ理論等）入門**
  舞鶴市多世代交流施設まなびあむ, 2022.

- **「行動経済学」とはどのような分野なのか？**
  シンポジウム「行動経済学の死」を考える(第2回), 2022.
  [講演資料（改訂版）へのリンク](https://www.dropbox.com/s/m9og4vjnzx3hacp/%E8%A1%8C%E5%8B%95%E7%B5%8C%E6%B8%88%E5%AD%A6%E3%81%A8%E3%81%AF%E3%81%A9%E3%81%AE%E3%82%88%E3%81%86%E3%81%AA%E5%88%86%E9%87%8E%E3%81%AA%E3%81%AE%E3%81%8B%EF%BC%9F%E6%94%B9%E8%A8%82%E7%89%88.pdf?dl=0)

- **行動経済学の概要と家事事件への応用**
  神戸家庭裁判所自庁研修, 2018.

- **家事調停の交渉場面における行動経済学**
  全国家庭裁判所調査官研究協議会, 2018

- **行動経済学**
  日本経済研究センター, 2014.

- **実務に生かす『行動経済学』**
  日本経済研究センター, 2013.（大竹文雄氏と共同）

- **ニュース解説バトル〜阪大秋の陣〜**
  Scienthrough, 2012.
  
- **経済実験で考える「給料のはなし」**
  Scienthrough, 2011.
