---
title: " "
pagetitle: "Tomoharu Mori"
---

<br>

## Peer-reviewed Journal Articles

<br>

- **The Ratchet Effect and the Probability of Proceeding to the Next Stage: An Experiment**
  *Bulletin of Economic Research*, forthcoming.
  (with Shigeo Morita)
  &nbsp;[Link]( https://doi.org/10.1111/boer.12448)

- **Loot Box Gambling and Economic Preferences: A Survey Analysis of Japanese Adolescents and Young Adults**
  *Applied Economics*, 55(44), 5213–5229, 2023.
  (with Tetsuya Kawamura, Yuhsuke Koyama, Taizo Motonishi, and Kazuhito Ogawa)
  &nbsp;[Link](https://doi.org/10.1080/00036846.2022.2138817)
  
- **Positive versus Negative Graphics for Increasing Attendance in a Cardiovascular Disease Prevention Program: A Randomized Controlled Trial**
  *Journal of Behavioral Economics and Finance*, 15, 22-30, 2022.
   (with Tetsuya Kawamura, Taizo Motonishi, and Kazuhito Ogawa)
   &nbsp;[Link](https://doi.org/10.11167/jbef.15.22)

- **Labor Supply Reaction to Wage Cuts and Tax Increases: A Real-Effort Experiment**
  *FinanzArchiv/Public Finance Analysis*, 78(3), 362-377, 2022.
  (with Hirofumi Kurokawa and Fumio Ohtake) 
  &nbsp;[Link](https://doi.org/10.1628/fa-2022-0008)

- **Is Financial Literacy Dangerous? Financial Literacy, Behavioral Factors, and Financial Choices of Households.**
  *Journal of the Japanese and International Economies*, 60, 101131, 2021.
  (with Tetsuya Kawamura, Taizo Motonishi, and Kazuhito Ogawa)
  &nbsp;[Link](https://doi.org/10.1016/j.jjie.2021.101131)

- **A Choice Experiment on Taxes: Are Income and Consumption Taxes Equivalent?**
  *Journal of Behavioral Economics and Finance*, 13, 53-70, 2020.
  (with Hirofumi Kurokawa and Fumio Ohtake) 
  &nbsp;[Link](https://doi.org/10.11167/jbef.13.53)

- **The Effects of Fixed-term Cashback Program on Exit Behavior: The Case of Osaka Municipal Housing Corporation.**
  *Urban Housing Sciences*, 84, 90-98, 2014.
  (with Fumio Ohtake, in Japanese) 
  &nbsp;[Link](https://doi.org/10.11531/uhs.2014.84_90)

<br>

## Journal Articles (Not Peer-Reviewed)

<br>

- **Behavioral Economics of Taxation and Benefits**
  *Public Policy Review*, 19(4), 1-28, 2023.
  &nbsp;[Link](https://doi.org/10.57520/prippr.19-4-3)

<br>

## Working Papers

<br>

- **Ambiguity and Loss aversion: The Effect of the Endowment and Windfall Losses on the Willingness to Pay for Insurance**
  (with Yasuhiro Nakamoto and Naoko Okuyama)
  &nbsp;[Link](https://www.kansai-u.ac.jp/riss/output/paper/pdf/RISS_DP_No85.pdf)

- **The Effect of Age, Gender, and Earned Income in the Trust Game: A Laboratory Experiment in Japan**
  (with Kazuhito Ogawa, in Japanese)
  &nbsp;[Link](https://www.kansai-u.ac.jp/riss/output/paper/pdf/RISS_DP_No40.pdf)
